luren-dc/QQMusicApi

pyqqmusicapi/api/__init__.py, pyqqmusicapi/api/singer.py, tests/test_singer.py
添加歌手api, 包括歌手信息，单曲，专辑，MV列表和相似歌手。
=> api: singer: add singer api

README.md, qqmusic_api/api/album.py, qqmusic_api/api/mv.py, qqmusic_api/api/singer.py, qqmusic_api/api/song.py, qqmusic_api/api/songlist.py, qqmusic_api/api/top.py, qqmusic_api/utils/credential.py
1. 优化`Song`,`Album`,`MV`,`Songlist`,`Singer`,`Top`的`print`输出
2. `Song`获取播放链接传入`Credential`
1. feat: `Song`,`Album`,`MV`,`Songlist`,`Singer`,`Top`的`__repr__`
2. feat: `Song.get_url`支持传入`Credential`
⚠️ 请自检并全部**勾选全部选项**。⚠️
=> 优化输出和功能增强：Song、Album、MV 等类的输出优化及播放链接获取改进

qqmusic_api/api/songlist.py
=> fix: 修改错误注释

qqmusic_api/utils/network.py
fix #23 
修复了获取会员歌曲无效
⚠️ 请自检并全部**勾选全部选项**。⚠️
=> fix: `Api`传入`Credential`无效

.github/workflows/testing.yml
=> ci: 更新测试ci

pyproject.toml, qqmusic_api/login.py, qqmusic_api/singer.py, qqmusic_api/utils/network.py, tests/test_login.py
=> refactor: 重构 `LoginApi` 代码

.pre-commit-config.yaml, Makefile, pdm.lock, pyproject.toml
=> chore: 部分 hooks 改为 local

.github/release.yml
This PR prepares for version 0.1.3.
=> Release v0.1.3

pyproject.toml, qqmusic_api/__init__.py
=> build: 更新 pyproject.toml

README.md, pdm.lock, pyproject.toml, qqmusic_api/__init__.py, qqmusic_api/album.py, qqmusic_api/data/api/album.json, qqmusic_api/login.py, qqmusic_api/singer.py, qqmusic_api/song.py, qqmusic_api/utils/network.py
=> release v0.1.5

qqmusic_api/data/api/song.json, qqmusic_api/song.py, tests/test_song.py
=> feat: 支持获取加密和试听文件

.github/workflows/docs.yml, examples/download_song.py, mkdocs.yml, qqmusic_api/album.py, qqmusic_api/song.py
=> feat: 支持获取 OGG 320kbps

.github/release.yml
=> ci: Create release.yml

.github/release-drafter.yml, .github/workflows/testing.yml, pdm.lock, pyproject.toml, qqmusic_api/__init__.py, qqmusic_api/login.py, qqmusic_api/song.py, tests/__init__.py, tests/conftest.py, tests/test_album.py, tests/test_login.py, tests/test_lyric.py, tests/test_mv.py, tests/test_search.py, tests/test_singer.py, tests/test_song.py, tests/test_songlist.py, tests/test_top.py, tests/test_user.py
=> feat: `get_song_urls` 更好的 Typing Hints

qqmusic_api/login.py, qqmusic_api/lyric.py, qqmusic_api/utils/network.py, qqmusic_api/utils/sync.py, qqmusic_api/utils/utils.py
=> fix: 修复获取逐字歌词未解析问题

qqmusic_api/album.py
=> feat: 支持获取专辑封面链接

qqmusic_api/__init__.py, qqmusic_api/utils/network.py, qqmusic_api/utils/qimei.py
=> feat: 支持 logging

docs/api/exceptions.md, docs/credential.md, docs/release-notes.md, docs/session.md, mkdocs.yml, qqmusic_api/exceptions/__init__.py, qqmusic_api/exceptions/api_exception.py, qqmusic_api/utils/network.py, qqmusic_api/utils/session.py, qqmusic_api/utils/sign.py, tests/test_sign.py, uv.lock
=> :sparkles: feat: 支持加密接口

qqmusic_api/singer.py
=> fix(singer): 修复地区代码错误

qqmusic_api/song.py, tests/test_song.py
=> feat(song): add get_fav_num function

main.py, qqmusic_api/singer.py, tests/test_singer.py
目前的get_songs()只有一个HasMore字段，不方便获得所有歌曲。
添加新的调用，可以获得当前歌手所有歌曲， 专辑， MV。
=> feat(singer): 添加获取全部歌曲，专辑，MV调用

qqmusic_api/songlist.py, tests/test_songlist.py, tests/test_user.py
歌单和歌曲的添加删除需要Credential， 因此把测试用例放在了 `test_user.py` 中。不过不知道写的对不对，麻烦看一下吧。谢谢！
=> feat(Songlist): 添加歌单处理函数

qqmusic_api/comment.py, tests/test_comments.py
=> ✨ feat: 添加获取精彩评论（歌曲热评）的能力

qqmusic_api/__init__.py, qqmusic_api/comment.py
=> 📝 docs(comment): 增加歌曲热评返回参数注释
